apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: loki-stack
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  repo: "https://github.com/joshrwolf/fleet-playground.git"
  paths:
  - apps/monitoring
